
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "SpaceWar_common.h"
namespace SpaceWar
{
	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_RequestServerConnect,
               
		Rmi_RequestNetworkGameTeamSelect,
               
		Rmi_RequestGameExit,
               
		Rmi_RequestNetworkGameReady,
               
		Rmi_RequestLobbyConnect,
               
		Rmi_RequestNetworkChangeMap,
               
		Rmi_RequestNetworkPlayerCount,
               
		Rmi_RequestNetworkGameModeChange,
               
		Rmi_RequestNetworkGameStart,
               
		Rmi_RequestNetworkHostOut,
               
		Rmi_RequestGameSceneJoin,
               
		Rmi_NotifyLoginSuccess,
               
		Rmi_NotifyLoginFailed,
               
		Rmi_NotifyNetworkUserSetup,
               
		Rmi_NotifyNetworkGameTeamChange,
               
		Rmi_NotifyNetworkConnectUser,
               
		Rmi_NotifyNetworkReady,
               
		Rmi_NotifyNetworkGameModeChange,
               
		Rmi_NotifyNetworkGamePlayerCountChange,
               
		Rmi_NotifyNetworkGameChangeMap,
               
		Rmi_NotifyNetworkGameStart,
               
		Rmi_NotifyNetworkGameStartFailed,
               
		Rmi_NotifyNetworkGameHostOut,
               
		Rmi_NotifyOtherClientJoin,
               
		Rmi_NotifyPlayerLost,
               
		Rmi_RequestHpUpdate,
               
		Rmi_RequestOxyUpdate,
               
		Rmi_NotifyPlayerChangeHP,
               
		Rmi_NotifyPlayerChangeOxygen,
               
		Rmi_RequestPlayerDamage,
               
		Rmi_RequestPlayerUseOxy,
               
		Rmi_NotifyPlayerMove,
               
		Rmi_NotifyPlayerEquipItem,
               
		Rmi_NotifyPlayerUnEquipItem,
               
		Rmi_NotifyPlayerBulletCreate,
               
		Rmi_NotifyPlayerBulletMove,
               
		Rmi_NotifyPlayerBulletDelete,
               
		Rmi_NotifyPlayerAnimation,
               
		Rmi_NotifyGrenadeCreate,
               
		Rmi_NotifyGrenadeMove,
               
		Rmi_NotifyGrenadeBoom,
               
		Rmi_NotifyGrenadeRemove,
               
		Rmi_RequestOxyChargerStartSetup,
               
		Rmi_RequestUseOxyChargerStart,
               
		Rmi_RequestUseOxyCharger,
               
		Rmi_RequestUseOxyChargerEnd,
               
		Rmi_NotifyUseOxyCharger,
               
		Rmi_NotifyUseSuccessedOxyCharger,
               
		Rmi_NotifyUseFailedOxyCharger,
               
		Rmi_RequestUseItemBox,
               
		Rmi_NotifyStartItemBoxState,
               
		Rmi_NotifyUseItemBox,
               
		Rmi_RequestShelterStartSetup,
               
		Rmi_RequestShelterDoorControl,
               
		Rmi_RequestShelterEnter,
               
		Rmi_NotifyShelterInfo,
               
		Rmi_RequestWorldCreateItem,
               
		Rmi_NotifyCreateItem,
               
		Rmi_RequestItemDelete,
               
		Rmi_NotifyDeleteItem,
               
		Rmi_NotifyNetworkObjectCreate,
               
		Rmi_NotifyNetworkObjectMove,
               
		Rmi_NotifyNetworkObjectDelete,
               
		Rmi_RequestMeteorCreate,
               
		Rmi_NotifyMeteorCreateTime,
               
		Rmi_NotifyMeteorCreate,
               
		Rmi_RequestSpaceShipSetup,
               
		Rmi_RequestSpaceShip,
               
		Rmi_RequestUseSpaceShip,
               
		Rmi_RequestUseSpaceShipCancel,
               
		Rmi_NotifyUseSpaceShipSuccess,
               
		Rmi_NotifyUseSpaceShipFailed,
               
		Rmi_NotifySpaceShipLockTime,
               
		Rmi_NotifySpaceShipEngineChargeFailed,
               
		Rmi_NotifySpaceShipEngineCharge,
               
		Rmi_NotifyDeathZoneCommingTime,
               
		Rmi_NotifyDeathZoneCreate,
               
		Rmi_RequestDeathZoneMoveIndex,
               
		Rmi_NotifyDeathZoneMoveHostAndIndexSetup,
               
		Rmi_NotifyDeathZoneMove,
               
		Rmi_NotifyDrawGame,
               
		Rmi_RequestDrawGameResult,
               
		Rmi_RequestGameEnd,
               
		Rmi_NotifyKillInfo,
               
		Rmi_NotifyGameResultInfoMe,
               
		Rmi_NotifyGameResultInfoOther,
               
		Rmi_NotifyGameResultShow,
               
		Rmi_NotifyUtilPlayerRebirth,
               
		Rmi_NotifyUtilPlayerDead,
               
		Rmi_RequestUtilMeteorCreate,
	};

	int g_RmiIDListCount = 90;
}
