
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "SpaceWar_common.h"
namespace SpaceWar
{
	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_RequestServerConnect,
               
		Rmi_RequestClientJoin,
               
		Rmi_RequestWorldCreateItem,
               
		Rmi_RequestPlayerDamage,
               
		Rmi_RequestPlayerUseOxy,
               
		Rmi_RequestUseOxyCharger,
               
		Rmi_RequestUseItemBox,
               
		Rmi_RequestShelterStartSetup,
               
		Rmi_RequestShelterDoorControl,
               
		Rmi_RequestShelterEnter,
               
		Rmi_NotifyLoginSuccess,
               
		Rmi_NotifyLoginFailed,
               
		Rmi_NotifyOtherClientJoin,
               
		Rmi_NotifyPlayerLost,
               
		Rmi_NotifyPlayerMove,
               
		Rmi_NotifyDeleteItem,
               
		Rmi_NotifyCreateItem,
               
		Rmi_NotifyStartOxyChargerState,
               
		Rmi_NotifyStartItemBoxState,
               
		Rmi_NotifyPlayerEquipItem,
               
		Rmi_NotifyPlayerUnEquipItem,
               
		Rmi_NotifyPlayerBulletCreate,
               
		Rmi_NotifyPlayerBulletMove,
               
		Rmi_NotifyPlayerBulletDelete,
               
		Rmi_NotifyPlayerAnimation,
               
		Rmi_NotifyPlayerChangeHP,
               
		Rmi_NotifyPlayerChangeOxygen,
               
		Rmi_NotifyUseOxyCharger,
               
		Rmi_NotifyUseItemBox,
               
		Rmi_NotifyShelterInfo,
               
		Rmi_NotifyMeteorCreateTime,
               
		Rmi_NotifyMeteorCreate,
               
		Rmi_NotifySpaceShipEngineCharge,
               
		Rmi_RequestGameEnd,
               
		Rmi_NotifyKillInfo,
               
		Rmi_NotifyGameResultInfoMe,
               
		Rmi_NotifyGameResultInfoOther,
               
		Rmi_NotifyGameResultShow,
	};

	int g_RmiIDListCount = 38;
}
